/* --------------------------------------------------------------------------------
 #
 #	4DPlugin.h
 #	source generated by 4D Plugin Wizard
 #	Project : USB
 #	author : miyako
 #	2015/03/22
 #
 # --------------------------------------------------------------------------------*/



// --- Device
void USB_DEVICE_LIST(sLONG_PTR *pResult, PackagePtr pParams);
void USB_DEVICE_Open(sLONG_PTR *pResult, PackagePtr pParams);
void USB_DEVICE_CLOSE(sLONG_PTR *pResult, PackagePtr pParams);

// --- I/O
void USB_Write_data(sLONG_PTR *pResult, PackagePtr pParams);
void USB_Read_data(sLONG_PTR *pResult, PackagePtr pParams);

// --- Init/deinit
void OnInitPlugin();
void OnCloseProcess();
bool IsProcessOnExit();

typedef PA_Unichar* process_name_t;

#include "libusb.h"

typedef struct{
    libusb_device_handle *dev;
    int interface_number;
} USB_T;

// --- Reference Management

bool DeviceOpen(C_LONGINT &index, C_LONGINT &vid, C_LONGINT &pid, C_LONGINT &interface);
void DeviceClose(C_LONGINT &index);
USB_T *DeviceGet(C_LONGINT &index);